# Travis-CI Build for Hangfire
# see travis-ci.org for details


language: csharp
solution: chezzles.cocossharp/chezzles.cocossharp.sln

install:
  - nuget restore chezzles.cocossharp/chezzles.cocossharp.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./chezzles.cocossharp/chezzles.cocossharp.sln /p:TargetFrameworkVersion="v4.5"
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./chezzles.cocossharp/chezzles.cocossharp/chezzles.Engine.Tests/bin/Release/chezzles.Engine.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
