# Travis-CI Build for Hangfire
# see travis-ci.org for details


language: csharp
solution: ./chezzles.cocosharp/chezzles.cocossharp.sln
mono:
  - latest
  - 3.12.0

install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./chezzles.cocosharp/chezzles.cocossharp.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./chezzles.cocossharp/chezzles.cocossharp/chezzles.Engine.Tests/bin/Release/chezzles.Engine.Tests.dll

# Only watch the master branch.
branches:
 only:
   - master
